apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  namespace: workers
spec:
  replicas: 0   # IMPORTANT: KEDA controls replicas
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: order-processor-sa
      containers:
        - name: order-processor
          image: jukpozi/order-processor:latest
          imagePullPolicy: Always

          env:
            - name: NERVE_CENTER_URL
              value: "http://nerve-center.core.svc.cluster.local:8080"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
