apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-processor-sa
  namespace: workers
  annotations:
    azure.workload.identity/client-id: '9c506b43-7045-4dfb-9b3e-5088a4f57b0d'
  labels:
    azure.workload.identity/use: "true"
