apiVersion: v1
kind: ServiceAccount
metadata:
  name: nerve-center-sa
  namespace: core
  annotations:
    azure.workload.identity/client-id: 632d969b-11c0-4b35-a930-77c936a8c7ae
  labels:
    azure.workload.identity/use: "true"
