apiVersion: v1
kind: Service
metadata:
  name: nerve-center
  namespace: core
spec:
  selector:
    app: nerve-center
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
