apiVersion: v1
kind: ServiceAccount
metadata:
  name: retry-worker-sa
  namespace: workers
  annotations:
    azure.workload.identity/client-id: '654d7474-65fd-431a-8fbe-deb05b5540d0'
  labels:
    azure.workload.identity/use: "true"
